# Generated by Django 3.0.8 on 2020-07-04 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasepost',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showcasepost',
            name='personality',
            field=models.CharField(default='default', help_text='The personality of the villager.', max_length=200),
        ),
        migrations.AddField(
            model_name='showcasepost',
            name='species',
            field=models.CharField(default=django.utils.timezone.now, help_text='The animal type of the villager.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showcasepost',
            name='teir',
            field=models.IntegerField(default=1, help_text='The teir of the villager (S, A, B, C, D).'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showcasepost',
            name='description',
            field=models.TextField(help_text='Description of the villager.', max_length=500),
        ),
    ]
