# Generated by Django 3.0.8 on 2020-07-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20200704_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcasepost',
            name='teir',
            field=models.CharField(help_text='The teir of the villager (S, A, B, C, D).', max_length=1),
        ),
    ]
