# Generated by Django 3.0.8 on 2020-07-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_auto_20200704_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcasepost',
            name='teir',
            field=models.CharField(default='A', help_text='The teir of the villager (S, A, B, C, D).', max_length=1),
        ),
    ]
