# Generated by Django 3.0.8 on 2020-07-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_remove_showcasepost_teir'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasepost',
            name='teir',
            field=models.IntegerField(default='1', help_text='The teir of the villager (S, A, B, C, D).', max_length=1),
        ),
    ]
