# Generated by Django 3.0.8 on 2020-07-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_showcasepost_teir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcasepost',
            name='teir',
        ),
    ]
