# Generated by Django 3.0.8 on 2020-07-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_showcasepost_teir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcasepost',
            name='personality',
            field=models.CharField(help_text='The personality of the villager.', max_length=200),
        ),
        migrations.AlterField(
            model_name='showcasepost',
            name='teir',
            field=models.CharField(help_text='The teir of the villager (S, A, B, C, D).', max_length=1),
        ),
    ]
