# Generated by Django 3.0.8 on 2020-07-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_auto_20200710_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcasepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
