# Generated by Django 3.0.8 on 2020-07-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0013_auto_20200710_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcasepost',
            name='image',
            field=models.URLField(),
        ),
    ]
