# Generated by Django 3.0.8 on 2020-07-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0014_auto_20200710_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcasepost',
            name='image',
            field=models.URLField(help_text='Enter a URL pointing to your image'),
        ),
    ]
