# Generated by Django 3.0.8 on 2020-07-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0015_auto_20200717_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcasepost',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='showcasepost',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='showcasepost',
            name='personality',
            field=models.CharField(max_length=200),
        ),
    ]
